services:
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=mydatabase'
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=myuser'
#    ports:
#      - '5432'

  mysql:
    image: 'mysql:latest'
    container_name: 'mysql'
    environment:
      - 'MYSQL_ROOT_PASSWORD=my-secret-pw'
      - 'MYSQL_ROOT_USER =root'
    ports:
      - '3306:3306'
